name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Pinhouse_env

    steps:
      # 1 소스 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ 멀티플랫폼(arm64) 빌드용 에뮬레이터
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 2 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3 Docker Hub 로그인
      - name: Login to Docker Hub (Access Token)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # 4 Frontend (Next.js) 이미지 빌드 & 푸시
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker-pinhouse-file
          push: true
          # ✅ 핵심: 멀티 플랫폼 manifest 생성
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/pinhouse:latest
            ${{ secrets.DOCKER_USERNAME }}/pinhouse:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_OAUTH2=${{ secrets.NEXT_PUBLIC_OAUTH2 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max